create database customer_behavior; 
use customer_behavior;
show tables;
select * from customers;
-- total revenue generated by male v/s female
select gender, sum(purchase_amount_usd) revenue from customers group by gender; 
-- customers that used discount but still spend more than the avg purchase amount
select 
	customer_id, 
    purchase_amount_usd 
from 
	customers 
where 
	discount_applied='Yes' 
    and purchase_amount_usd>=(select avg(purchase_amount_usd) from customers);
-- top 5 products with the highest avg review ratings
select 
	item_purchased, 
    avg(review_rating) 
from 
	customers 
group by 
	item_purchased
order by 
	avg(review_rating) desc limit 5;
-- avg purchase amount b/w standard and express shipping
select avg(purchase_amount_usd) avg_shipping_charge, shipping_type from customers where shipping_type in ('Express', 'Standard') group by shipping_type;
-- do subscribe customers spend more?
select 
	count(customer_id) total_customers, 
    sum(purchase_amount_usd) total_revenue, 
    avg(purchase_amount_usd) avg_Spending, 
    case 
		when subscription_status='Yes' then 'Subscriber'
        else 'Not a Subscriber' 
	end Subscription 
from 
	customers 
where 
	subscription_status in ('Yes', 'No') 
group by 
	subscription_status;
-- top 5 products with highest percentage of purchases with discount applied
select item_purchased, round(((sum(case when discount_applied='Yes' then 1 else 0 end ))/count(*))*100, 2) as discount_rate from customers group by item_purchased order by discount_rate desc limit 5;
-- Categorize customers as new, returning and loyal based on their total number of previous purchases and display the count of each segment
with customer_segment as (
	select 
	case 
		when previous_purchases = 1 then 'New'
        when previous_purchases between 2 and 10 then 'Returning'
        else 'Loyal'
	end Customer_Segment,
    customer_id
		from customers		
)
select customer_segment, count(customer_id) from customer_segment group by customer_segment;
-- top 3 most purchased product within each category
with item_count as(
	select 
		category, 
        item_purchased, 
        count(customer_id) total_orders, 
        row_number() over(partition by category order by count(customer_id) desc)as item_rank 
	from 
		customers 
	group by 
		category, 
        item_purchased
)
select category, item_purchased, total_orders, item_rank from item_count where item_rank<4;
-- are customers who are repeat buyers(more than 5 times) likely to subscribe
select subscription_status, count(customer_id) repeat_buyers from customers where previous_purchases>5 group by subscription_status;
-- revenue contribution of each age group
select sum(purchase_amount_usd), age_group from customers group by age_group